// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiah8qE2qqVMvZowkIt5-fZ35QTTqbhjA',
    appId: '1:390752342931:web:fb654205d60594ece8ce66',
    messagingSenderId: '390752342931',
    projectId: 'shift-planner-dev',
    authDomain: 'shift-planner-dev.firebaseapp.com',
    storageBucket: 'shift-planner-dev.appspot.com',
    measurementId: 'G-DFV2QCCM6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkhsLFYMIsBYFyPT9clbtzoyK4v19fJtw',
    appId: '1:390752342931:android:2e7dc7186f5b9c6de8ce66',
    messagingSenderId: '390752342931',
    projectId: 'shift-planner-dev',
    storageBucket: 'shift-planner-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvdb18takHFKzGsbgvlp2E-L0KwHY8Ds',
    appId: '1:390752342931:ios:2441b5d503b83e67e8ce66',
    messagingSenderId: '390752342931',
    projectId: 'shift-planner-dev',
    storageBucket: 'shift-planner-dev.appspot.com',
    iosClientId: '390752342931-2l5fj32ni4g5brmcevo5hg5nj1h6bs0f.apps.googleusercontent.com',
    iosBundleId: 'com.dexter.health.shift.planner.dev',
  );
}
