name: app_ui
description: UI Toolkit for the ShiftPlanner Flutter Application
version: 0.0.2-dev.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.4

flutter:
