name: task_repository
description: Handles tasks on firebase
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  authentication_repository:
  collection: ^1.16.0
  cloud_firestore: ^4.2.0
  dart_code_metrics: ^4.17.1
  equatable: ^2.0.3
  fast_immutable_collections: ^7.4.1
  fpdart: ^0.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  freezer: ^0.6.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
